"""EU Parliament Election Data.

Member states with MEP allocations, political groups with ideological
positions, and country-specific party strength weights.

Sources: European Parliament (2024-2029 term), EU Political Groups.
"""

EU_MEMBER_STATES = {
    "Germany": 96,
    "France": 81,
    "Italy": 76,
    "Spain": 61,
    "Poland": 53,
    "Romania": 33,
    "Netherlands": 31,
    "Belgium": 22,
    "Czech Republic": 21,
    "Greece": 21,
    "Hungary": 21,
    "Portugal": 21,
    "Sweden": 21,
    "Austria": 20,
    "Bulgaria": 17,
    "Denmark": 15,
    "Finland": 15,
    "Slovakia": 15,
    "Ireland": 14,
    "Croatia": 12,
    "Lithuania": 11,
    "Latvia": 9,
    "Slovenia": 9,
    "Estonia": 7,
    "Cyprus": 6,
    "Luxembourg": 6,
    "Malta": 6,
}

EU_POLITICAL_GROUPS = {
    "EPP": {
        "name": "European People's Party",
        "position_x": 0.3,
        "position_y": -0.2,
        "valence": 65,
        "color": "#003399",
    },
    "S&D": {
        "name": "Socialists & Democrats",
        "position_x": -0.3,
        "position_y": -0.3,
        "valence": 60,
        "color": "#ED1B24",
    },
    "Renew": {
        "name": "Renew Europe",
        "position_x": 0.1,
        "position_y": -0.4,
        "valence": 55,
        "color": "#FFD700",
    },
    "Greens/EFA": {
        "name": "Greens/European Free Alliance",
        "position_x": -0.4,
        "position_y": -0.5,
        "valence": 50,
        "color": "#00A651",
    },
    "ECR": {
        "name": "European Conservatives and Reformists",
        "position_x": 0.5,
        "position_y": 0.3,
        "valence": 45,
        "color": "#0054A5",
    },
    "ID": {
        "name": "Identity and Democracy",
        "position_x": 0.6,
        "position_y": 0.6,
        "valence": 40,
        "color": "#003366",
    },
    "Left": {
        "name": "The Left (GUE/NGL)",
        "position_x": -0.6,
        "position_y": -0.1,
        "valence": 40,
        "color": "#990000",
    },
    "NI": {
        "name": "Non-Inscrits (Non-attached)",
        "position_x": 0.0,
        "position_y": 0.5,
        "valence": 30,
        "color": "#808080",
    },
}

COUNTRY_GROUP_WEIGHTS = {
    "Germany": {
        "EPP": 0.28,
        "S&D": 0.20,
        "Greens/EFA": 0.15,
        "Renew": 0.12,
        "Left": 0.08,
        "ECR": 0.10,
        "ID": 0.05,
        "NI": 0.02,
    },
    "France": {
        "Renew": 0.22,
        "ID": 0.25,
        "EPP": 0.10,
        "S&D": 0.15,
        "Greens/EFA": 0.08,
        "Left": 0.10,
        "ECR": 0.05,
        "NI": 0.05,
    },
    "Italy": {
        "ECR": 0.30,
        "S&D": 0.20,
        "EPP": 0.10,
        "Renew": 0.08,
        "Greens/EFA": 0.05,
        "Left": 0.05,
        "ID": 0.15,
        "NI": 0.07,
    },
    "Spain": {
        "EPP": 0.35,
        "S&D": 0.30,
        "Renew": 0.05,
        "Greens/EFA": 0.05,
        "Left": 0.12,
        "ECR": 0.08,
        "ID": 0.03,
        "NI": 0.02,
    },
    "Poland": {
        "EPP": 0.35,
        "ECR": 0.30,
        "S&D": 0.10,
        "Renew": 0.08,
        "Left": 0.05,
        "Greens/EFA": 0.02,
        "ID": 0.05,
        "NI": 0.05,
    },
    "_default": {
        "EPP": 0.25,
        "S&D": 0.20,
        "Renew": 0.15,
        "Greens/EFA": 0.10,
        "ECR": 0.12,
        "ID": 0.08,
        "Left": 0.05,
        "NI": 0.05,
    },
}
